import type { Theme } from "overtype";

/** Oldworld palette applied to OverType — hex values from the Oldworld VS Code theme. */
export const OLDWORLD_OVERTYPE_THEME: Theme = {
  name: "oldworld",
  colors: {
    bgPrimary: "transparent",
    bgSecondary: "transparent",
    text: "#c9c7cd",
    textPrimary: "#c9c7cd",
    textSecondary: "#9f9ca6",
    placeholder: "#8b8693",
    primary: "#aca1cf",
    h1: "#aca1cf",
    h2: "#92a2d5",
    h3: "#92a2d5",
    strong: "#d19a66",
    em: "#e29eca",
    del: "#ea83a5",
    link: "#90b99f",
    code: "#90b99f",
    codeBg: "rgba(172, 161, 207, 0.08)",
    blockquote: "#e29eca",
    hr: "#b4b1ba",
    listMarker: "#b4b1ba",
    rawLine: "#9f9ca6",
    syntax: "#9f9ca6",
    syntaxMarker: "#8b8693",
    cursor: "#9c9ca6",
    selection: "#aca1cf4a",
    border: "#313134",
    hoverBg: "#2a2a2c",
    toolbarBg: "#1b1b1c",
    toolbarIcon: "#c9c7cd",
    toolbarHover: "#2a2a2c",
    toolbarActive: "#aca1cf",
    toolbarBorder: "#313134",
  },
};
